### PR TITLE
added title image

### PR DESCRIPTION
**Pull request by xmonish**
Signed-off-by: Monish Singh <36487698+xmonish@users.noreply.github.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [x] Fixes #<issue number>
-   [x] Signed the commit for DCO to be passed
-   [x] Labelled this PR & related issue with `documentation` tag

### CODE REVIEW

**Comment by xmonish** [comment]
Done with the DCO now :)

**Review by divya-mohan0209 — DISMISSED** [review]
LGTM, approved.

**Comment by ksatchit** [comment]
Can you please place the logo beside the title text as shown here: https://github.com/litmuschaos/litmus/blob/master/README.md

**Comment by xmonish** [comment]
Please ignore the multiple uploads. It was done by mistake.

Signed-off-by: Monish Singh <36487698+xmonish@users.noreply.github.com>

**Comment by ksatchit** [comment]
Thanks @xmonish !!

**Review by ksatchit — APPROVED** [review]
LGTM

**Pull request merged**
