### PR TITLE
improving README

### LINKED ISSUE #2099: Improve our documentation by adding explanations and examples
#### SUMMARY

Litmus's current documentation and README could be improved further. If you find something lacking any form of good description about Litmus perhaps consider adding those details.

For Documentation related contribution take a look into this repository [https://github.com/litmuschaos/litmus-docs](https://github.com/litmuschaos/litmus-docs)

> **Suggestion:** To begin with you can contribute to the *getting started with litmus* docs [https://github.com/litmuschaos/litmus-docs/blob/master/docs/getstarted.md](https://github.com/litmuschaos/litmus-docs/blob/master/docs/getstarted.md)

You can choose to improve any README.md file by adding in examples in the form of screenshots or improving on the details.

#### EASY README FILES TO IMPROVE

* Litmus Portal Readme ([https://github.com/litmuschaos/litmus/blob/master/litmus-portal/README.md](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/README.md))
* Litmus Portal Frontend Readme ([https://github.com/litmuschaos/litmus/blob/master/litmus-portal/frontend/README.md](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/frontend/README.md))

#### ISSUE TYPE

* Documentation Improvement

#### CONTACT PERSON

* [Sayan Mondal](https://github.com/S-ayanide)
* [Prithvi Raj](https://github.com/prithvi1307)

Thanks for taking the time to read this issue. In order for Litmus to clarify your doubts effectively, provide us a few hours to reply back.

### PR DESCRIPTION
**Pull request by 3scava1i3r**
some minute changes in main heading with addition of various badges to make a better visual appeal

**What this PR does / why we need it**:
some minute changes in main heading with addition of various badges to make a better visual appeal

**Special notes for your reviewer**:

**Checklist:**
-    Fixes  https://github.com/litmuschaos/litmus/issues/2099
-   Labelled this PR & related issue with `documentation` tag

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
@3scava1i3r : Please note that your PR has not passed any checks. Kindly check the details & resubmit the PR appropriately

**Comment by 3scava1i3r** [comment]
> @3scava1i3r : Please note that your PR has not passed any checks. Kindly check the details & resubmit the PR appropriately

all the checks have passed here 
image

**Review by S-ayanide — APPROVED** [review]

**Review by divya-mohan0209 — APPROVED** [review]
LGTM. @k8s-dev @ksatchit : Your thoughts, please.

**Review by ksatchit — APPROVED** [review]

**Comment by 3scava1i3r** [comment]
I would like to know that this PR was merged and according to https://blog.mayadata.io/celebrate-hacktoberfest-2020-open-source-with-mayadata
how will i be contacted?

**Pull request merged**
