### PR TITLE
Update Footer Logo and install command

### PR DESCRIPTION
**Pull request by anupriya0703**
- [x] Updated footer Litmus logo
image

- [x] Updated install command under getting started page

Signed-off-by: anupriya0703 <anupriya.gupta@mayadata.io>

### CODE REVIEW

**Review by ranjithwingrider — CHANGES_REQUESTED** [review]
remove duplicate `kubectl apply`  in getting started

**Review by ranjithwingrider — CHANGES_REQUESTED** [review]
Update `Documentation` in  `version-0.7.0-sidebars.json` under `versioned_sidebars`
No need to change on sidebars.json since with latest docusarus version it is maintaining sidrbars with corresponding version

**Review by ranjithwingrider — APPROVED** [review]
Looks good..

**Review by qiell — APPROVED** [review]
Lgtm

**Review by ajeshbaby — APPROVED** [review]

**Pull request merged**
