### PR TITLE
removed deprecated field in Travis config

### PR DESCRIPTION
**Pull request by StrikerRUS**
Signed-off-by: Nikita Titov <nekit94-12@hotmail.com>

Refer to https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration.

> In the next phase of the migration, all builds will run on virtual-machine-based infrastructure – regardless of the configuration for `sudo` in the `.travis.yml`.

> Soon we will run all projects on the virtual-machine-based infrastructure, the sudo keyword will be fully deprecated.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
gently ping @rahulchheda @ksatchit @chandankumar4

**Comment by ksatchit** [comment]
Hey @StrikerRUS ! Thank you for your patience. There is a bit of chat about this in the group. The link says "sudo: false" is the entry to be removed, if present, while the `sudo` keyword maybe deprecated "going ahead/soon". Is the latter already in place? Could you please share some references/throw some light on this? Thank you!!

**Comment by StrikerRUS** [comment]
@ksatchit Sure! In that post you can find the following:

> Soon we will run all projects on the virtual-machine-based infrastructure, the sudo keyword will be fully deprecated.

> 07 December, 2018 - All projects that use a Linux build environment will be fully migrated to using the same Linux infrastructure, which runs builds in virtual-machines.

**Review by chandankumar4 — APPROVED** [review]
Thanks @StrikerRUS for your contribution

**Comment by NisantaSahoo** [comment]
Thanks for taking part in Hacktoberfest 2019. Please fill up this form to claim your swag https://hubs.ly/H0l5ldm0

**Pull request merged**
