### PR TITLE
Image optimise

### LINKED ISSUE #77: Optimise images
- Convert RGBA PNG to Indexed-RGB PNG
- Compress JPG images

### PR DESCRIPTION
**Pull request by aravindvnair99**
Fixes https://github.com/litmuschaos/litmus-docs/issues/77

### CODE REVIEW

**Review by chandankumar4 — APPROVED** [review]
Thanks, @aravindvnair99 For optimizing the images

**Comment by aravindvnair99** [comment]
> Thanks, @aravindvnair99 For optimizing the images

@chandankumar4 Glad to contribute and help! :)

**Review by anupriya0703 — APPROVED** [review]
lgtm

**Comment by NisantaSahoo** [comment]
Thanks for taking part in Hacktoberfest 2019. Please fill up this form to claim your swag https://hubs.ly/H0l5ldm0

**Pull request merged**
