### PR TITLE
Upgrading docusaurus version to 1.13.0

### PR DESCRIPTION
**Pull request by aswathkk**
Upgrades docusaurus to latest version as mentioned in the issue [#820](https://github.com/litmuschaos/litmus/issues/820)

### CODE REVIEW

**Comment by umamukkara** [comment]
Thank you @aswathkk  for this PR. GIve us sometime to review this as this a big PR. Can you upload some screenshots of your local instance?

**Comment by kmjayadeep** [comment]
Hi @aswathkk 
looks like the changes in latest PR's are not there in your repo.
You might need to rebase against current staging and update the docs content.

I was just looking for my changes in PR https://github.com/litmuschaos/litmus-docs/pull/40 . But probably there will be more

**Comment by kmjayadeep** [comment]
Search functionality is not working. It was not working on the old version either.
The edit button on the pages in 0.5 is not pointed to the right github files it seems.

@umamukkara I'm just wondering.., the 0.5 version seems to have much more content about the internal architecture and setting up of litmus. Is there any specific reason why those were removed from 0.6?

On the other hand, the new UI looks far better than old one

**Comment by ksatchit** [comment]
Thanks @aswathkk ! Please correct me, is it possible to break this PR into smaller PRs/changes?

**Comment by kmjayadeep** [comment]
The Dockerfile and docker-compose.yml file needs some changes. I'm not sure whether we should make all changes in one giant PR though.

- Avoid `expose` commands in build-env part in Dockerfile as it is not required
- Avoid using `yarn` commands and use `npm` in Dockerfile, as `yarn.lock` is removed from the repo.
- Could you please explain why you have used custom nginx configuration? Ideally just copying the build dir to `/usr/share/nginx/html` should work
- Docker compose file doesn't need `volumes` and `working_dir` as Dockerfile is copying those directories anyway
- docker-compose should be used to build the entire container, not just the `build-env` stage
- It might be a good idea to add a `image` tag in docker-compose. Maybe `litmuschaos/litmus-docs` ?
- Dockerfile needs a restructuring. `package.json` and `package-lock.json` should be copied first and run the `npm install` command. Copying the source code and building should be done after this. Otherwise everytime a change is made to the source code, it will build the entire container from scratch. This way, it would cache the npm dependencies.
- WORKDIR should be /app
- Maybe in the docker-compose we need to expose port 80 as 3000. It's generally not a good idea to expose as a port under 1000

Sorry for the long list of changes. I would be happy to assist in Dockerfile and docker-compose as it is my area of expertise

**Comment by aswathkk** [comment]
> Thank you @aswathkk for this PR. GIve us sometime to review this as this a big PR. Can you upload some screenshots of your local instance?

@umamukkara Here's it!
Screenshot 2019-10-09 at 9 36 30 PM
Screenshot 2019-10-09 at 9 38 02 PM
I hope this would be sufficient as it resolves the issue with the responsiveness.

> Hi @aswathkk
looks like the changes in latest PR's are not there in your repo.
You might need to rebase against current staging and update the docs content.
I was just looking for my changes in PR #40 . But probably there will be more

@kmjayadeep Thanks for finding it out. I will pull and rebase.

> The edit button on the pages in 0.5 is not pointed to the right github files it seems.

@kmjayadeep  It is pointing to the right files in Github. Which is present in */docs* directory.

> Thanks @aswathkk ! Please correct me, is it possible to break this PR into smaller PRs/changes?

@ksatchit That's why I broke the whole PR into multiple commits.
- The first 3 commits just delete unwanted files. (please refer the commit message)
- 4th one adds files into .gitignore & .dockerignore. (I just copied whatever generated by Docusaurus)
- I know 5th one is large. But the thing is that most of them are generated as part of versioning in Docusaurus.
Initially, I copied MD files and Sidebar of **v0.5.0** branch into */docs*. Then I ran `yarn version 0.5.0`. It generated the files present at `versioned_docs/version-0.5.0` and `versioned_sidebars/version-0.5.0`.
After doing so, I copied MD files and sidebar files from **staging** branch to */docs*. Then I ran `yarn version 0.6.0`. It generated the files present at `versioned_docs/version-0.6.0` and `versioned_sidebars/version-0.6.0`
- I think, 6th and 7th commits are not huge and I mentioned what it does in the commit message. Please refer that.

Btw, How should I split this PR into multiple PRs?

**Comment by aswathkk** [comment]
> - Avoid expose commands in build-env part in Dockerfile as it is not required
> - Docker compose file doesn't need volumes and working_dir as Dockerfile is copying those directories anyway
> - docker-compose should be used to build the entire container, not just the build-env stage
> - It might be a good idea to add a image tag in docker-compose. Maybe litmuschaos/litmus-docs ?
> - Maybe in the docker-compose we need to expose port 80 as 3000. It's generally not a good idea to expose as a port under 1000

Here, docker-compose file is used to setup a development environment. For production, any way we are using TravisCI

> - Avoid using yarn commands and use npm in Dockerfile, as yarn.lock is removed from the repo.

In the Docusaurus docs, they are using yarn. Actually, we don't need the lock files since we won't be installing any new packages. All those things are managed by Docusaurus. That's why they added lock files into .gitignore.

> - Dockerfile needs a restructuring. package.json and package-lock.json should be copied first and run the npm install command. Copying the source code and building should be done after this. Otherwise everytime a change is made to the source code, it will build the entire container from scratch. This way, it would cache the npm dependencies.

I totally agree!

> - WORKDIR should be /app

package.json is not present in */app*. It is present inside */app/website*. So we can't do `yarn install`

> - Could you please explain why you have used custom nginx configuration? Ideally just copying the build dir to /usr/share/nginx/html should work

You are right. No need of that file.
It is used in the previous version to fix the redirection issue. But now, we are managing redirection in the index.html itself.
I'm not sure whether other directives are needed in the nginx config file or not.

**Comment by ksatchit** [comment]
> Btw, How should I split this PR into multiple PRs?

- Thanks for the detailed explanation on the commits, @aswathkk . Totally get the autogenerated content. Was wondering if these changes could be made as part of separate/multiple PRs for ease of review. However, I see the dockerfile/ignorefile/docs additions are closely tied to the version changes (js/docusaurus noob here!). Adding the experts for review.

**Comment by qiell** [comment]
Thanks for the PR @aswathkk 

Some comments from my side, 
1. We need the collapsible sidebar, have a look at https://docusaurus.io/docs/en/navigation#collapsible-categories
2. Search is not working.

I'll happy to help you with this.

**Comment by aswathkk** [comment]
@qiell Collapsible sidebar makes sense for v0.5.0 of docs since it has a sizable amount of content. But in the case of v0.6.0, it's not much. That's why I didn't enable it.
What are your thoughts on it?

The search is not working in the [Production docs](https://docs.litmuschaos.io/) itself. I thought I will concentrate only on upgrading docusaurus version.

**Comment by qiell** [comment]
@aswathkk 
> Collapsible sidebar makes sense for v0.5.0 of docs since it has a sizable amount of content. But in the case of v0.6.0, it's not much. That's why I didn't enable it.
What are your thoughts on it?

For v0.6.0, contents are still in progress. So, I think we can go ahead with `collapsible` sidebar. Once contents are in place, we don't need to raise a PR for the same.

>The search is not working in the Production docs itself. I thought I will concentrate only on upgrading docusaurus version.

Sure. I'll take a look at production docs and let you know why it is not working.

**Comment by qiell** [comment]
One more thing @aswathkk 
In Production docs, we have `GitHub` and `Slack` in the navigation bar. Can you add both of them here as well?

**Comment by aswathkk** [comment]
> One more thing @aswathkk
In Production docs, we have GitHub and Slack in the navigation bar. Can you add both of them here as well?

@qiell Its there in the footer. But since the "Chaos Hub" link in the header is feeling lonely, I will add Slack and Github link in the header too. :wink:

**Comment by aswathkk** [comment]
I just rebased to the staging branch.

@qiell I made the sidebar collapsible and added links in the header as you suggested.

**Review by mayacloud — APPROVED** [review]

**Review by qiell — APPROVED** [review]
Thanks for the changes @aswathkk

I am approving the PR.
It looks good to me.

**Review by chandankumar4 — APPROVED** [review]
lgtm

**Comment by NisantaSahoo** [comment]
Thanks for taking part in Hacktoberfest 2019. Please fill up this form to claim your swag https://hubs.ly/H0l5ldm0

**Pull request merged**
