### PR TITLE
Added installation and demo of litmus

### PR DESCRIPTION
**Pull request by imrajdas**
Added following things:
- [x] Installation
- [x] Demo
- [x] cleanup

### CODE REVIEW

**Review by umamukkara — APPROVED** [review]
LGTM

**Comment by ksatchit** [comment]
@rajdas98 , let us not cleanup by removing ns -- it might be better to explain by delete -f of the  operator, engine yamls & crds.

There are chances ns deleteion is stuck - or even if succeeded, the stale engine, exp, results will still remain causing auto-start of experiments next time they install operator

**Review by ajeshbaby — COMMENTED** [review]
We support in all  OS environments.

**Comment by ajeshbaby** [comment]
Also how about having a single file to install all the 3 commands.  RBAC, CRDs and Operator,

**Pull request merged**
