### PR TITLE
back to top button

### PR DESCRIPTION
**Pull request by auralshin**
Back to top button in litmuschaos-docs site #56

### CODE REVIEW

**Comment by anupriya0703** [comment]
@auralshin Hi! Thanks for contributing. Can you also attach updated screenshot?(With this button)

**Comment by auralshin** [comment]
@anupriya0703 the website is written in mark up lannguage and by opening through cloned repository it's not loading. So I can't take  screenshot.

**Comment by inyee786** [comment]
@auralshin , have you tested the code?
check out the README.md https://github.com/litmuschaos/litmus-docs for local setup

**Comment by chandankumar4** [comment]
Closing this stale PR

**Pull request closed without merging**
