### PR TITLE
Added github-action workflow for Spelling Checks in Latest Docs.

### PR DESCRIPTION
**Pull request by Jonsy13**
Signed-off-by: Jonsy13 <vedant.shrotria@chaosnative.com>

**What this PR does / why we need it**:

**This PR will add Github-Action Workflow for Spelling-checks in the latest Docs.**

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #litmuschaos/litmus#1943

**Special notes for your reviewer**:

**Checklist:**
-   [X] Fixes #litmuschaos/litmus#1943
-   [X] Signed the commit for [DCO](https://github.com/litmuschaos/litmus-docs/blob/master/CONTRIBUTING.md#sign-your-work) check to be passed
-   [ ] Labelled this PR & related issue with `documentation` tag

### CODE REVIEW

**Comment by Jonsy13** [comment]
**DO_NOT_MERGE**,Will try to update the wordlist.txt.

**Comment by Jonsy13** [comment]
@ksatchit, PR is ready now.
For now, I have added all the unique words which were giving errors in the dictionary.
We can modify the dictionary progressively.

**Review by uditgaurav — DISMISSED** [review]

**Comment by ksatchit** [comment]
Great, thanks @Jonsy13 ! I suppose the dictionary needs cleanup, some of the text items there need to be removed and fixed - but I suppose we could do that refinement in a separate PR. More of a doc author AI IMO !

**Review by ksatchit — DISMISSED** [review]

**Comment by Jonsy13** [comment]
@ksatchit @uditgaurav This PR is ready now.
I checked the wordlist, there are some words that can be removed and docs can also be updated, will update them in a separate PR.

**Review by uditgaurav — DISMISSED** [review]
Looks Good to me. Thanks @Jonsy13.
@k8s-dev do you also want to take a look?

**Comment by Jonsy13** [comment]
@uditgaurav @ksatchit 
This PR is ready, I have resolved the embedmd issues and some conflicts.
Do take a look, as embedmd has commented some code (Node selector property ).

**Review by uditgaurav — APPROVED** [review]

**Pull request merged**
