### PR TITLE
Fixes

### LINKED ISSUE #68: Header and navigation issues
- The title is overlapped by the navigation.
- Hamburger button on the navigation is not in place.

Will submit a PR.

### PR DESCRIPTION
**Pull request by aravindvnair99**
Fixes #68 

- Fixed page title being overlapped by the navigation.
- Fixed hamburger button on the navigation not being in place.

### CODE REVIEW

**Review by msj2 — APPROVED** [review]
Kudos.

**Review by aswathkk — CHANGES_REQUESTED** [review]
@aravindvnair99 Thanks for figuring it out.
In most of the other markdown files, the same CSS is present which breaks the UI.
Would you please modify those as well?

**Comment by aravindvnair99** [comment]
> @aravindvnair99 Thanks for figuring it out.
> In most of the other markdown files, the same CSS is present which breaks the UI.
> Would you please modify those as well?

Sure @aswathkk , will have a look at it.

**Comment by chandankumar4** [comment]
Thanks @aravindvnair99 for your contribution, Can you add the image also for the clarity of what you are trying to fix

**Comment by aravindvnair99** [comment]
> Thanks @aravindvnair99 for your contribution, Can you add the image also for the clarity of what you are trying to fix

@chandankumar4 I'm sorry, I didn't understand. Do you mean a screenshot of before-after?

**Comment by chandankumar4** [comment]
> > Thanks @aravindvnair99 for your contribution, Can you add the image also for the clarity of what you are trying to fix
> 
> @chandankumar4 I'm sorry, I didn't understand. Do you mean a screenshot of before-after?

yes

**Review by anupriya0703 — APPROVED** [review]
LGTM

**Review by chandankumar4 — APPROVED** [review]
LGTM

**Comment by NisantaSahoo** [comment]
Thanks for taking part in Hacktoberfest 2019. Please fill up this form to claim your swag https://hubs.ly/H0l5ldm0

**Pull request merged**
