### PR TITLE
Fix wrong description for CPU_CORES option in pod-cpu-hog experiment

### LINKED ISSUE #265: Wrong description for CPU_CORES
Hello. Found the wrong description for CPU_CORES parameter
https://github.com/litmuschaos/litmus-docs/blob/bc25b995389c75aed0aa7dad1a34fc4d5b7e6e13/docs/pod-cpu-hog.md#supported-experiment-tunables

### PR DESCRIPTION
**Pull request by Jasstkn**
Signed-off-by: Jasstkn <jasssstkn@yahoo.com>

closes #265

### CODE REVIEW

**Review by ksatchit — DISMISSED** [review]

**Comment by ksatchit** [comment]
Thanks @Jasstkn for reporting and fixing this!

**Comment by Jasstkn** [comment]
> Thanks @Jasstkn for reporting and fixing this!

the description is valid?
> Number of the cpu cores subjected to CPU stress

**Comment by ksatchit** [comment]
You might also want to push this changes to the versioned doc here: https://github.com/litmuschaos/litmus-docs/blob/master/website/versioned_docs/version-1.3.0/pod-cpu-hog.md

**Comment by ksatchit** [comment]
> > Thanks @Jasstkn for reporting and fixing this!
> 
> the description is valid?
> 
> > Number of the cpu cores subjected to CPU stress

think so. the current mechanism doesn't utilize it "fully" yet - so it is just stress (varies from ~70-90% ) depending on base image.

**Comment by Jasstkn** [comment]
> You might also want to push this changes to the versioned doc here: https://github.com/litmuschaos/litmus-docs/blob/master/website/versioned_docs/version-1.3.0/pod-cpu-hog.md

will do.

**Review by ksatchit — APPROVED** [review]

**Pull request merged**
