### PR TITLE
introducing scheduler

### PR DESCRIPTION
**Pull request by Sanjay1611**
This PR contains `Constructing Scheduler` inside `Concepts` field of sidebar
Here are the few screenshots -
Screenshot from 2020-05-13 20-52-04
Screenshot from 2020-05-13 20-52-38

Signed-off-by: Sanjay Nathani <sanjay.nathani@mayadata.io>

### CODE REVIEW

**Comment by ksatchit** [comment]
Nice @Sanjay1611 !

**Comment by ksatchit** [comment]
While this is the detailed construction doc, can we have a separate sidebar item under "Experiments" that gives a brief intro about chaos scheduling with an example of pod-delete ? (lets add a note that it is alpha)

**Comment by Sanjay1611** [comment]
Added note for version alpha 
Screenshot from 2020-05-14 12-51-30

**Comment by Sanjay1611** [comment]
Sample ChaosSchedule inside pod-delete experiment
Screenshot from 2020-05-14 12-52-26

**Comment by Sanjay1611** [comment]
Added scheduling tab and removed it from `pod-delete` experiment
Screenshot from 2020-05-14 16-13-31

**Review by ksatchit — APPROVED** [review]

**Review by chandankumar4 — APPROVED** [review]

**Pull request merged**
