### PR TITLE
(fix): refined python script

### PR DESCRIPTION
**Pull request by StrikerRUS**
Signed-off-by: Nikita Titov <nekit94-12@hotmail.com>

Removed unused import, unused variable `wd`, trailing whitespaces.

Made it possible to call this script from any folder by opening file with absolute path.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
gently ping @rahulchheda @ksatchit @chandankumar4

**Review by chandankumar4 — APPROVED** [review]
Thanks, @StrikerRUS for your contribution

**Review by ksatchit — APPROVED** [review]

**Review by aditya109 — APPROVED** [review]
LGTM

**Comment by NisantaSahoo** [comment]
Thanks for taking part in Hacktoberfest 2019. Please fill up this form to claim your swag https://hubs.ly/H0l5ldm0

**Pull request merged**
