### PR TITLE
(feat)(docs)(initial): Create Litmus Docs

### PR DESCRIPTION
**Pull request by ksatchit**
## Changes
-------------

- Phase #1 consists of Introduction, Concepts & User Guide
- Diagrams will be included in subsequent PRs 

Signed-off-by: ksatchit <karthik.s@openebs.io>

### CODE REVIEW

**Comment by ksatchit** [comment]
image

**Comment by Pradeepkumarbk** [comment]
@ksatchit can you replace the hotjar code with the new one?

**Comment by ksatchit** [comment]
> @ksatchit can you replace the hotjar code with the new one?

@Pradeepkumarbk , are the applied changes appropriate?

**Review by Pradeepkumarbk — APPROVED** [review]
LGTM

**Review by umamukkara — APPROVED** [review]

**Pull request merged**
