### PR TITLE
Update pod-delete.md

### PR DESCRIPTION
**Pull request by aushafy**
i have been tested on Tanzu Kubernetes Grid Integrated (TKGi) K8s Platform and it's work

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] Signed the commit for DCO to be passed
-   [ ] Labelled this PR & related issue with `documentation` tag

### CODE REVIEW

**Comment by ksatchit** [comment]
Hey @aushafy ! Thanks for the tests & creating PR.

**Comment by ksatchit** [comment]
Would you be open to running other tests too? Would be great if you could put the results in a gist file for reference

**Comment by aushafy** [comment]
> Would you be open to running other tests too? Would be great if you could put the results in a gist file for reference

yes i would test all Experiment on the same platform

**Comment by ksatchit** [comment]
> > Would you be open to running other tests too? Would be great if you could put the results in a gist file for reference
> 
> yes i would test all Experiment on the same platform

Great, looking forward to the results - maybe this PR can include updates on other experiments in the "Generic" suite!! 
Also, request you to please [sign](https://github.com/litmuschaos/litmus-docs/blob/master/CONTRIBUTING.md#sign-your-work) your commit.

**Comment by aushafy** [comment]
for sure, i will make a sign later. thanks

**Review by ksatchit — APPROVED** [review]

**Comment by ksatchit** [comment]
Will be merging this PR, we can have a separate once covering other experiments!

**Pull request merged**
