### PR TITLE
Changed the ChaosEngine YAML, added step to override defaults

### PR DESCRIPTION
**Pull request by rahulchheda**
Files Changes are self-explanatory.

**Change Log**
- Added the `monitoring` field in the sample chaosEngine Spec
- Removed Rank in `spec.experiements[*].components`
- Added ENV Over-ride in sample chaosEngine at `spec.experiments[*].components.name[*]`
- Change the experiment in the sample ChaosEngine
- Added a section to override the variables in chaosExperiment, after section Prepare ChaosEngine

**Latest Logs**
```
rahul@rahul-ThinkPad-E490:~/go-dev/src/github.com/litmuschaos/litmus-docs/website$ npm start

> @0.0.0 start /home/rahul/go-dev/src/github.com/litmuschaos/litmus-docs/website
> docusaurus-start

LiveReload server started on port 35729
Docusaurus server started on port 3000
```

### CODE REVIEW

**Review by ksatchit — DISMISSED** [review]

**Review by imrajdas — DISMISSED** [review]

**Review by ksatchit — DISMISSED** [review]

**Review by anupriya0703 — DISMISSED** [review]
LGTM

**Comment by chandankumar4** [comment]
@rahulchheda do we need package-lock file?

**Comment by rahulchheda** [comment]
> @rahulchheda do we need package-lock file?

Yes, for npm package it's needed

**Comment by chandankumar4** [comment]
> > @rahulchheda do we need package-lock file?
> 
> Yes, for npm package it's needed

Can you check again, As per the updated readme `package-lock.json` is not required.

**Review by chandankumar4 — APPROVED** [review]
LGTM

**Pull request merged**
