### PR TITLE
added logo in the top

### PR DESCRIPTION
**Pull request by xmonish**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [x] Fixes #<issue number>
-   [x] Labelled this PR & related issue with `documentation` tag

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
LGTM. Please sign the DCO & resubmit the PR

**Review by divya-mohan0209 — CHANGES_REQUESTED** [review]
LGTM. Please sign the DCO & resubmit the PR

**Comment by xmonish** [comment]
> LGTM. Please sign the DCO & resubmit the PR

Where will i find the DCO?

**Comment by divya-mohan0209** [comment]
> > LGTM. Please sign the DCO & resubmit the PR
> 
> Where will i find the DCO?

Please check the details hyperlink in the Checks section. It has instructions on how this needs to be done.

**Comment by xmonish** [comment]
> > > LGTM. Please sign the DCO & resubmit the PR
> > 
> > 
> > Where will i find the DCO?
> 
> Please check the details hyperlink in the Checks section. It has instructions on how this needs to be done.

Got it. Thanks for such an early response! Will do this asap.

**Review by xmonish — COMMENTED** [review]
Signed-off-by: Monish Singh <monishsingh26@gmail.com>

**Comment by xmonish** [comment]
@divya-mohan0209 Please check if it's done or not...

**Comment by divya-mohan0209** [comment]
> @divya-mohan0209 Please check if it's done or not...

Please commit the changes properly. Merely adding a comment will not help it pass the DCO.

**Comment by xmonish** [comment]
> > @divya-mohan0209 Please check if it's done or not...
> 
> Please commit the changes properly. Merely adding a comment will not help it pass the DCO.

I'm new to DCO, can you please tell me is there a way to fix this without using git?
Thanks.

**Comment by divya-mohan0209** [comment]
@xmonish : You need to use the GIT CLI.

To fix, first ensure you have a local copy of your branch by checking out the pull request locally via command line. Next, head to your local branch and run:

git commit --amend --signoff
Now your commits will have your sign off. Next run

git push --force-with-lease origin patch-1

**Comment by xmonish** [comment]
> @xmonish : You need to use the GIT CLI.
> 
> To fix, first ensure you have a local copy of your branch by checking out the pull request locally via command line. Next, head to your local branch and run:
> 
> git commit --amend --signoff
> Now your commits will have your sign off. Next run
> 
> git push --force-with-lease origin patch-1

Getting "Error: Failed to push some refs" after the 2nd step

**Comment by divya-mohan0209** [comment]
Please checkout a local copy before you actually commit anything. Once you have checked it out, please commit the code with the message. Then push the changes.

**Comment by xmonish** [comment]
Updated the DCO in the new PR.

**Comment by divya-mohan0209** [comment]
DCO is still pending & there are merge conflicts.

**Comment by ksatchit** [comment]
Seems to be a duplicate PR of https://github.com/litmuschaos/litmus-docs/pull/384. Closing in favour of that.

**Pull request closed without merging**
