### PR TITLE
added versioned docs for example page

### LINKED ISSUE #905: [litmus-docs] Need to update instructions as per 0.7
The instructions in `getting started` and `chaos example` are not working since the installation step has changed to install version 0.7 of litmus. This is a blocker for new users who are trying to get started with litmus.

Only one change I know is that chaosengine.yaml `spec.appinfo` now requires `kind` attribute to be specified.

If someone from the contributors can help with the changelog, I can help to test and create PR with the updated instructions.

### Steps to reproduce

1. Open https://docs.litmuschaos.io/docs/getstarted/
2. Follow the guide to setup an experiment
3. Observe that experiment is not being run
4. Repeat 1-3 with https://docs.litmuschaos.io/docs/example/

### PR DESCRIPTION
**Pull request by kmjayadeep**
- Copied example.md to versioned docs 0.7 so that we can have different versions, similar to other pages.
- Added `appkind: deployment` in chaosengine.yaml to make it compatible with 0.7
- Litmus operator yaml file link is changed to include version number (similar to getting started page)
- Modified link to getting started page to use relative path instead of absolute url (as specified in https://docusaurus.io/docs/en/navigation

No other changes in md file

fixes litmuschaos/litmus#905

Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>

### CODE REVIEW

**Comment by kmjayadeep** [comment]
@ksatchit It seems like `appkind` is only required in next release and not in 0.7. I have tested with 0.7 operator without `appkind` and it worked. Can you please confirm this?

**Comment by chandankumar4** [comment]
@kmjayadeep The example file is not required in 0.7 can you just update the `example` page link in `getstarted` page

**Comment by kmjayadeep** [comment]
> @kmjayadeep The example file is not required in 0.7 can you just update the `example` page link in `getstarted` page

Wouldn't that be a problem when we release new docs for 0.8?
I think it is better to keep a uniform structure for all files

**Comment by chandankumar4** [comment]
> > @kmjayadeep The example file is not required in 0.7 can you just update the `example` page link in `getstarted` page
> 
> Wouldn't that be a problem when we release new docs for 0.8?
> I think it is better to keep a uniform structure for all file

> > @kmjayadeep The example file is not required in 0.7 can you just update the `example` page link in `getstarted` page
> 
> Wouldn't that be a problem when we release new docs for 0.8?
> I think it is better to keep a uniform structure for all files

The file adding in versioned docs is done by docusaurus, it's not the manual step, File is added to the released version only when the file contains the changes from previous release.
Closing this PR as this is not required.

**Comment by kmjayadeep** [comment]
@chandankumar4 Thanks for the explanation.
One additional note: The litmus operator yaml file in the doc is still pointing to latest version (post 0.7) instead of 0.7 itself. So, https://github.com/litmuschaos/litmus/issues/905 is still open!

**Comment by chandankumar4** [comment]
Yes, Thanks for noticing, Can you raise a fix for that?

**Pull request closed without merging**
